// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Test.Context;

namespace Test.Context.Configurations
{
    public partial class TasksConfiguration : IEntityTypeConfiguration<Tasks>
    {
        public void Configure(EntityTypeBuilder<Tasks> entity)
        {
            entity.Property(e => e.Description)
                .HasMaxLength(70)
                .IsUnicode(false);

            entity.Property(e => e.DueDate).HasColumnType("date");

            entity.Property(e => e.Title)
                .HasMaxLength(60)
                .IsUnicode(false);

            entity.HasOne(d => d.AssigneeNavigation)
                .WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Assignee)
                .HasConstraintName("FK__Tasks__Assignee__440B1D61");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tasks> entity);
    }
}
